---
title: Personality assessment from social media text
author: Knut Jägersberg
date: '2022-05-28'
slug: []
categories:
  - Data Science
  - Psychology
tags:
  - Personality assessment
---


# How to predict personality from social media data

Just a headline to draw relevant interest. Personally, I am not a huge fan of training a classifier for personality assessment and using that in a direct way to assess personality. 
There are many datasets available that fit the 16 personality types according to the broadly known work by Myers–Briggs. What you need is an assessment of how strong certain traits are prevalent, not binary yes no answers as often implied by such classifiers. 


## Thoughts on my preferences on usually underlying personality theory 
On the other hand, the theoretical work behind the types is often prematurely discarded, I'm not on a witch hunt after a type theorists, even though putting people into these buckets is in many cases a gross oversimplification. We know the indicators results correlate with the big 5. Also retest correlations of the magnitude of the cognitive functions are comparable to those of the big 5. There is more to the theory than acknowledged by the academic community, the overlap is not a coincidence. 
The big 5 / global 5 are properly the best validated instrument, whilst the theoretical framework underlying the personality type indicator captures tendencies of explanatory power. 


## How I want to use social media texts for personality assessment
My take is in line with the overall approach of Statement-to-Item Matching Personality Assessment (see https://www.sciencedirect.com/science/article/pii/S0167739X21004957): Use the big 5 framework for measurement but also extend it with data using with my own expert judgment and apply an interpretation of the results using patterns emerging from reasoning with Jungs cognitive functions (which, while the semantics of the wording can be disputed in many ways must capture general differences due to their overlap with the big 5). The tons of self-assessment personality type data from social media is of course useful for this, though I do not recommend to just train a type classifier. 

More concretely speaking, how will I do the mapping? Researchers have been able to re-score the type indicator to big 5 scale dimensions (see http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.555.3131&rep=rep1&type=pdf) and found a similar five factor solution for type indicator items as the one for the big 5. Using these items, the big 5 inventory scale items and dimension names are a good seed for extracting relevant phrases from social media. Furthermore, clusters in the outerances of people falling into the types can uncover some valid phrases indicating big 5 dimensions as picked by expert judgment. 
Then, on a per case basis, retrieve statements that match / are similar to these statements. I don't think aggregation is easily doable without introducing arbitrariness (although attempts have been made, with limited success, see Statement-to-Item Matching Personality Assessment ), so I see this more as a qualitative research tool for HUMINT. The task of ML is to improve and speed up LISTENING to the life story of the subject of interest, not being a tool of direct use like a psychological test, because of limitations in the technology as well as the inherent biases of any social media data you can tie to a name (i.e. favorable self-presentation). 
The workflow I see is listening to the life-story, forming hypotheses on major traits followed by further investigation on then easy to retrieve evidence and counter-evidence, so the human analyst can form their holistic impression more easily. 


## The datasets

1. Twitter data with the type indicators
2. Mypersonality dataset small with big 5 measurements
3. Reddit data with self assigned type indicators
4. A forum about the 16 personalities
5. Big 5 dimensions and adjectives
6. Big 5 inventory items
7. Overlapping type indicator items per big 5 dimension


